import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const dashboard = fs.readFileSync(path.resolve(here, "../booster-dashboard.html"), "utf8");

assert.match(dashboard, /id="threeDpSyncJournal"/);
assert.match(dashboard, /onclick="refreshThreeDpSyncJournal\(\)"/);
assert.match(dashboard, /function renderThreeDpSyncJournal\(\)/);
assert.match(dashboard, /call\('sync_journal',\{limit:20\}\)/);
assert.match(dashboard, /\['created','updated','noop'\]/);
assert.match(dashboard, /success\?'chip':'issue-tag'/);
assert.match(dashboard, /threeDpEsc\(row\.detail\)/);
assert.match(dashboard, /threeDpEsc\(row\.order_id\)/);
assert.match(dashboard, /threeDpEsc\(row\.timestamp_kyiv\)/);
assert.match(dashboard, /function migrateThreeDpLegacyModels\(\)/);
assert.match(dashboard, /threeDpLegacyModelLinks/);
assert.match(dashboard, /row && row\['РРЦ фактична, грн'\]/);
assert.match(dashboard, /row && row\['Ціна під викуп, грн'\]/);
assert.match(dashboard, /row && row\['Посилання на модель'\]/);
assert.match(dashboard, /Клас маржі до split/);
assert.match(dashboard, /\(РРЦ − собівартість Сергія\) ÷ РРЦ, до поділу 50\/50/);
assert.match(dashboard, /\['Q',rrp,'РРЦ фактична, грн'\]/);
assert.match(dashboard, /\['R',buyout,'Ціна під викуп, грн'\]/);
assert.match(dashboard, /\['S',model,'Посилання на модель'\]/);
assert.match(dashboard, /\['defect_rate',5,'Планований брак, частка','частка \(0\.1 = 10%\)'\]/);
assert.equal((dashboard.match(/range:'A1:C5'/g) || []).length, 2);
assert.doesNotMatch(dashboard, /range:'A1:C4'/);
assert.match(dashboard, /baseCost=material\+electricity\+amortization,cost=baseCost\*\(1\+defectRate\)/);
assert.match(dashboard, /Плановий брак/);
assert.match(dashboard, /<script src="\.\.\/3d-print\/shared\/print-time\.js"><\/script>/);
assert.match(dashboard, /function threeDpPrintTime\(value\)/);
assert.match(dashboard, /Сумарний час партії, год<input type="text" inputmode="decimal"/);
assert.match(dashboard, /Можна: 1:30, 1 год 30 хв або 1,5/);
assert.match(dashboard, /threeDpPrintTimeDisplay\(metrics\.time\)/);
assert.match(dashboard, /threeDpPrintTimeWarning\(metrics\.time\)/);
assert.match(dashboard, /f==='total_print_time_h'\?\(printTime\.ok && !printTime\.blank\?printTime\.hours:NaN\)/);
assert.doesNotMatch(dashboard, /function threeDpLatest\(/);
assert.doesNotMatch(dashboard, /function saveThreeDpModel\(/);

const validatorSource = dashboard.match(/function threeDpSkuTypeError\(sku,type\) \{[^\n]+\}/)?.[0];
assert.ok(validatorSource, "threeDpSkuTypeError must remain a standalone validator");
const validatorContext = vm.createContext({ String, RegExp });
vm.runInContext(`${validatorSource}\nglobalThis.validate = threeDpSkuTypeError;`, validatorContext);
assert.equal(validatorContext.validate("ACC-3D-DITTO-410", "Функціональний аксесуар"), "");
assert.equal(validatorContext.validate("ACC-3D-OP-500", "Функціональний аксесуар"), "");
assert.equal(validatorContext.validate("BR-CHARM-001", "Брелок"), "");
assert.match(validatorContext.validate("ACC-3D-410", "Функціональний аксесуар"), /ACC-3D-PKM-130/);
assert.match(validatorContext.validate("ACC-3D-DITTO-410", "Брелок"), /Префікс SKU/);

console.log("3dp-sync-journal dashboard static tests passed");
